on:
  push:
    branches:
      - main
  pull_request:
name: ci
jobs:
  linkinator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          skip: "CHANGELOG.md"
      - uses: ./
        with:
          paths: list.txt
          concurrency: 1
          markdown: false
          linksToSkip: "http://fake.local, http://fake.local/fake"
          format: csv
          
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm test
      - uses: codecov/codecov-action@v3
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm run lint
  ncc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          token: ${{ secrets.BECKWITH_ROBOT_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm run build
      - name: git config
        run: |
          git config user.name freshyill
          git config user.email freshyill@gmail.com@gmail.com
      - name: git push
        run: |
          git commit -a -m 'npm run build' || echo 'no changes'
          git push
